<?php

return [
    '⚽ Football' => 'Football',
    '🎾 Tennis' => 'Tennis',
    '🏀 Basketball' => 'Basketball',
    '🏎️ Automobile / course' => 'Automobile',
    '🏸 Badminton' => 'Badminton',
    '⚾ Baseball' => 'Baseball',
    '🏖️ Beach Volley' => 'Beach Volley',
    '🎯 Biathlon' => 'Biathlon',
    '🥊 Boxe' => 'Boxe',
    '🚴 Cyclisme' => 'Cyclisme',
    '🏈 Football américain' => 'Football américain',
    '🏉 Football australien' => 'Football australien',
    '🏎️ Formule 1' => 'Formule 1',
    '⛳ Golf' => 'Golf',
    '🤾 Handball' => 'Handball',
    '🏒 Hockey sur glace' => 'Hockey sur glace',
    '🎮 Esports' => 'Esports',
    '🥋 MMA / arts martiaux' => 'MMA',
    '🏍️ Moto' => 'Moto',
    '🏉 Rugby à XV' => 'Rugby à XV',
    '🏉 Rugby à XIII' => 'Rugby à XIII',
    '🎿 Ski alpin' => 'Ski alpin',
    '⛷️ Ski de fond' => 'Ski de fond',
    '🏂 Snowboard' => 'Snowboard',
    '🎱 Snooker / billard' => 'Snooker',
    '🏓 Tennis de table / Ping Pong' => 'Tennis de table',
    '🏐 Volley-ball' => 'Volley-ball',
    '🏃 Athlétisme' => 'Athlétisme',
    '🏊 Natation' => 'Natation',
    '🤽 Water polo' => 'Water polo',
    '🚣 Canoë / kayak' => 'Canoë / Kayak',
    '🏏 Cricket' => 'Cricket',
    '❓ Autre' => 'Autre',
];